### ISSUE TITLE
Link shortcuts to account

### ISSUE THREAD

**Issue by JustIanJ** [codeman1o1/codeman1o1.me#2]
make an account system and let us add our own shortcuts to sites we want. personal

**Comment by JustIanJ** [comment]
MAYBE SOMETHING WITH MONGO db?

**Comment by JustIanJ** [comment]
OR SOMETHING SIMILAR?

**Comment by codeman1o1** [comment]
Hey,
I think accounts are a bit out of the scope of this project.
I could store any custom apps on the client, but that also means that the configuration is only stored on that browser
